plugins {
    `java-library`
}

// PXF codec built against `protobuf-javalite` for Android (and any other JVM
// target where the descriptor-rich `protobuf-java` is too heavy). The codec
// is wire-equivalent with the full-runtime `:pxf` module — divergence is a
// CI-blocking regression — but consumes a `PxfMeta` table generated by
// `protoc-gen-pxf-java-meta` instead of `Descriptors.Descriptor`.
//
// Classpath isolation: `protobuf-java` is excluded transitively. If a
// descriptor-typed import sneaks into a source file, the test task fails to
// compile. That's the contract enforcement.

dependencies {
    api(project(":pxf-runtime"))
    api("com.google.protobuf:protobuf-javalite:3.25.5")

    configurations.all {
        exclude(group = "com.google.protobuf", module = "protobuf-java")
    }
}
