// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.
plugins {
    `java-library`
}

// SBE codec built against `protobuf-javalite` for Android (and any other
// JVM target where the descriptor-rich `protobuf-java` is too heavy).
// Wire-equivalent with the full-runtime `:sbe` module — divergence is a
// CI-blocking regression — but consumes a `MessageTemplate` data carrier
// generated by `protoc-gen-pxf-java-meta` (lite mode) instead of
// `Descriptors.Descriptor`.
//
// Architecturally this module is a thin facade: the actual descriptor-
// free codec (`SbeWireCodec`, `SbeFieldReader`/`Writer`, `MessageTemplate`,
// `View`, `XmlSchema`, `SbeConstants`) lives in `:sbe-runtime`. The role
// of this module is to be the published Maven artifact under
// `org.protowire:sbe-android` that Android / lite-tier consumers depend
// on, parallel to `:pxf-android`. Re-exports `:sbe-runtime` via `api` so
// downstream code can use `org.protowire.sbe.runtime.*` directly.
//
// Classpath isolation: `protobuf-java` is excluded transitively. If a
// descriptor-typed import sneaks into a source file in this module or a
// downstream consumer's lite-only target, the test/compile task fails
// to resolve it. That's the contract enforcement.

dependencies {
    api(project(":sbe-runtime"))
    api("com.google.protobuf:protobuf-javalite:4.36.1")

    configurations.all {
        exclude(group = "com.google.protobuf", module = "protobuf-java")
    }
}

// No sources of its own beyond package-info, so there is nothing for javadoc
// to document; the published artifact carries an empty javadoc jar (see the
// root build).
tasks.withType<Javadoc>().configureEach { enabled = false }
