// SPDX-License-Identifier: MIT
// Copyright (c) 2026 TrendVidia, LLC.
package org.protowire.pxf;

import com.google.protobuf.Duration;
import org.junit.jupiter.api.Test;
import org.protowire.pxf.testproto.AllTypes;

import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Every {@code google.protobuf.Duration} the other ports write can be read
 * here to the same seconds/nanos (#55), and this port's own output reads
 * back too. Mirrors {@code TestMarshalDurationReadsBack} in
 * {@code protowire-go/encoding/pxf/full_roundtrip_test.go}: the same
 * durations, with the text {@code time.Duration.String()} produces for
 * each generated by Go itself (a {@code go run} over the same list) rather
 * than transcribed.
 */
class DurationReadBackTest {

    private record Case(long nanos, String goText) {}

    private static final List<Case> CASES = List.of(
            new Case(0, "0s"),
            new Case(1, "1ns"),
            new Case(999, "999ns"),
            new Case(1000, "1µs"),
            new Case(1234, "1.234µs"),
            new Case(1500, "1.5µs"),
            new Case(312500, "312.5µs"),
            new Case(1234567, "1.234567ms"),
            new Case(1500000, "1.5ms"),
            new Case(1001000, "1.001ms"),
            new Case(2300000, "2.3ms"),
            new Case(250_000_000, "250ms"),
            new Case(1_000_000_000, "1s"),
            new Case(1_500_000_000, "1.5s"),
            new Case(5_400_000_000_000L, "1h30m0s"),
            new Case(5_400_500_000_000L, "1h30m0.5s"),
            new Case(5_445_123_456_789L, "1h30m45.123456789s"),
            new Case(360_000_000_000_000L, "100h0m0s"),
            new Case(-1, "-1ns"),
            new Case(-1500, "-1.5µs"),
            new Case(-312500, "-312.5µs"),
            new Case(-1_500_000_000, "-1.5s"),
            new Case(-5_400_500_000_000L, "-1h30m0.5s"),
            new Case(Long.MAX_VALUE, "2562047h47m16.854775807s"),
            new Case(Long.MIN_VALUE, "-2562047h47m16.854775808s"));

    // google.protobuf.Duration keeps seconds and nanos with the same sign
    // (-1ns is seconds 0, nanos -1), unlike java.time's positive nanos.
    private static Duration proto(long nanos) {
        return Duration.newBuilder()
                .setSeconds(nanos / 1_000_000_000L)
                .setNanos((int) (nanos % 1_000_000_000L))
                .build();
    }

    private static Duration decode(String text) {
        AllTypes.Builder b = AllTypes.newBuilder();
        Pxf.unmarshal(text.getBytes(StandardCharsets.UTF_8), b);
        return b.getDurField();
    }

    // The interop direction: text another port wrote.
    @Test
    void goDurationStringsReadBackExactly() {
        for (Case c : CASES) {
            assertEquals(proto(c.nanos()), decode("dur_field = " + c.goText()), c.goText());
        }
    }

    // This port's own output (whole units: 1500ms, 1234567ns) reads back
    // too, before and after the lexer change.
    @Test
    void ownOutputReadsBack() {
        for (Case c : CASES) {
            AllTypes msg = AllTypes.newBuilder().setDurField(proto(c.nanos())).build();
            String text = new String(Pxf.marshal(msg), StandardCharsets.UTF_8);
            assertTrue(text.contains("dur_field = "), text);
            assertEquals(proto(c.nanos()), decode(text), text);
        }
    }
}
