package org.protowire.pxf;

import java.util.Map;
import java.util.Set;

/**
 * Per-message descriptor metadata in a form the lite-runtime codec can use
 * without touching {@code com.google.protobuf.Descriptors}. Implementations
 * are typically generated by {@code protoc-gen-pxf-java-meta} from the
 * source {@code .proto} file and then plugged into the runtime by passing
 * a {@code FOO_PXF_META.INSTANCE} reference.
 *
 * <p>The shape mirrors the static tables emitted by the codegen plugin —
 * see the source-of-truth Javadoc on {@code <Message>PxfMeta} for the
 * authoritative description of each field.
 */
public interface PxfMeta {

    /** Field name → field number, in declaration order. */
    Map<String, Integer> fieldNumbers();

    /**
     * Field number → {@code FieldDescriptorProto.Type} integer (1..18).
     * E.g. 9 = STRING, 11 = MESSAGE, 14 = ENUM. Stable across protobuf
     * versions.
     */
    Map<Integer, Integer> fieldKinds();

    /** Field number → wire type (0=varint, 1=i64, 2=length-delimited, 5=i32). */
    Map<Integer, Integer> wireTypes();

    /** Field numbers labeled {@code repeated}. */
    Set<Integer> repeatedFields();

    /** Field numbers using packed encoding. */
    Set<Integer> packedFields();

    /**
     * Field number → fully-qualified Java class name of the target message,
     * for fields of kind 11 (MESSAGE).
     */
    Map<Integer, String> messageTypes();

    /**
     * Field number → fully-qualified Java class name of the target enum,
     * for fields of kind 14 (ENUM).
     */
    Map<Integer, String> enumTypes();

    /** Field numbers marked {@code [(pxf.required) = true]}. */
    Set<Integer> requiredFields();

    /**
     * Field number → {@code (pxf.default)} PXF text literal. Values are
     * unparsed PXF literals (e.g. {@code "42"}, {@code "\"hi\""}); the
     * caller routes them through the same lexer that handles user input.
     */
    Map<Integer, String> defaults();

    /** {@code (sbe.template_id)} value, or {@code -1} if the message is not an SBE template. */
    int sbeTemplateId();

    /** Field number → {@code (sbe.length)} byte length, where set. */
    Map<Integer, Integer> sbeFieldLengths();

    /** Field number → {@code (sbe.encoding)} primitive name, where set. */
    Map<Integer, String> sbeFieldEncodings();

    /**
     * Field number → declaring oneof name. Synthetic oneofs around proto3
     * {@code optional} fields are excluded; only user-declared oneof
     * groupings appear here.
     */
    Map<Integer, String> oneofOf();

    /**
     * The proto package + simple name of the described message, e.g.
     * {@code "sample.Person"}. Useful for diagnostics and for resolving
     * cross-message references in {@link #messageTypes()}.
     */
    String fullName();

    /**
     * Field number → {@link PxfMeta} of the target nested message type, for
     * fields of kind 11 (MESSAGE). Generated {@code <Message>PxfMeta} classes
     * populate this with direct {@code <Sub>PxfMeta.INSTANCE} references at
     * codegen time, so the runtime can recurse into nested messages without
     * a separate {@link PxfRegistry} lookup. Default returns {@link Map#of()}
     * — implementors that don't expose embedded references fall back to the
     * registry path.
     */
    default Map<Integer, PxfMeta> nestedMetas() {
        return Map.of();
    }

    /**
     * Field number → {@link PxfEnum} of the target enum type, for fields of
     * kind 14 (ENUM). Same shape and rationale as {@link #nestedMetas()};
     * default returns {@link Map#of()}.
     */
    default Map<Integer, PxfEnum> enumMetas() {
        return Map.of();
    }

    /**
     * Field numbers declared as {@code map<K, V>} in the source {@code .proto}.
     * Wire-format-wise, a map field is {@code repeated MapEntry}, where the
     * synthetic {@code MapEntry} sub-message has {@code key = 1} and
     * {@code value = 2}. The runtime cannot distinguish a map field from a
     * plain repeated submessage by its wire shape alone, so the codegen
     * plugin records the distinction here at build time. Default empty;
     * implementations that don't carry this distinction are interpreted as
     * "no map fields", and {@code repeated MapEntry}-style blocks fall
     * through to the regular nested-message path.
     */
    default Set<Integer> mapFields() {
        return Set.of();
    }

    /**
     * Field number → well-known-type kind, for fields whose target message is
     * one of the recognized PXF/Google WKTs. Drives the lite-runtime decoder's
     * fast path: instead of recursing into the submessage as a generic
     * {@code BlockVal}, the decoder synthesizes the canonical bare literal
     * (e.g. {@code "2024-01-01T00:00:00Z"} for {@code google.protobuf.Timestamp})
     * that a hand-written PXF document would use. Re-encoding either form via
     * {@link org.protowire.pxf.android.LiteWireWriter LiteWireWriter} produces
     * the same wire bytes, so this is purely a textual-canonicalization step.
     *
     * <p>Constants in {@link PxfMeta} ({@code WKT_TIMESTAMP}, {@code WKT_BIG_INT},
     * etc.). The codegen plugin populates this from the field's target message
     * FQN at build time. Default empty — hand-built {@code PxfMeta} implementations
     * that omit this map cause the decoder to fall through to its generic
     * nested-message path, which still round-trips correctly, just not through
     * the bare literal form.
     */
    default Map<Integer, Integer> wellKnownKinds() {
        return Map.of();
    }

    // --- Well-known type kind constants ----------------------------------------
    //
    // Stable integers that the codegen plugin emits in WELL_KNOWN_KINDS tables
    // and the lite runtime branches on. Adding new WKTs is fine; renumbering
    // existing ones breaks every previously-generated PxfMeta.

    int WKT_NONE         = 0;
    int WKT_TIMESTAMP    = 1;  // google.protobuf.Timestamp
    int WKT_DURATION     = 2;  // google.protobuf.Duration
    int WKT_STRING_VALUE = 3;  // google.protobuf.StringValue
    int WKT_BYTES_VALUE  = 4;  // google.protobuf.BytesValue
    int WKT_BOOL_VALUE   = 5;  // google.protobuf.BoolValue
    int WKT_INT32_VALUE  = 6;  // google.protobuf.Int32Value
    int WKT_INT64_VALUE  = 7;  // google.protobuf.Int64Value
    int WKT_UINT32_VALUE = 8;  // google.protobuf.UInt32Value
    int WKT_UINT64_VALUE = 9;  // google.protobuf.UInt64Value
    int WKT_FLOAT_VALUE  = 10; // google.protobuf.FloatValue
    int WKT_DOUBLE_VALUE = 11; // google.protobuf.DoubleValue
    int WKT_BIG_INT      = 12; // pxf.BigInt
    int WKT_DECIMAL      = 13; // pxf.Decimal
    int WKT_BIG_FLOAT    = 14; // pxf.BigFloat
}
