package org.protowire.pxf;

import java.util.Map;
import java.util.Set;

/**
 * Per-message descriptor metadata in a form the lite-runtime codec can use
 * without touching {@code com.google.protobuf.Descriptors}. Implementations
 * are typically generated by {@code protoc-gen-pxf-java-meta} from the
 * source {@code .proto} file and then plugged into the runtime by passing
 * a {@code FOO_PXF_META.INSTANCE} reference.
 *
 * <p>The shape mirrors the static tables emitted by the codegen plugin —
 * see the source-of-truth Javadoc on {@code <Message>PxfMeta} for the
 * authoritative description of each field.
 */
public interface PxfMeta {

    /** Field name → field number, in declaration order. */
    Map<String, Integer> fieldNumbers();

    /**
     * Field number → {@code FieldDescriptorProto.Type} integer (1..18).
     * E.g. 9 = STRING, 11 = MESSAGE, 14 = ENUM. Stable across protobuf
     * versions.
     */
    Map<Integer, Integer> fieldKinds();

    /** Field number → wire type (0=varint, 1=i64, 2=length-delimited, 5=i32). */
    Map<Integer, Integer> wireTypes();

    /** Field numbers labeled {@code repeated}. */
    Set<Integer> repeatedFields();

    /** Field numbers using packed encoding. */
    Set<Integer> packedFields();

    /**
     * Field number → fully-qualified Java class name of the target message,
     * for fields of kind 11 (MESSAGE).
     */
    Map<Integer, String> messageTypes();

    /**
     * Field number → fully-qualified Java class name of the target enum,
     * for fields of kind 14 (ENUM).
     */
    Map<Integer, String> enumTypes();

    /** Field numbers marked {@code [(pxf.required) = true]}. */
    Set<Integer> requiredFields();

    /**
     * Field number → {@code (pxf.default)} PXF text literal. Values are
     * unparsed PXF literals (e.g. {@code "42"}, {@code "\"hi\""}); the
     * caller routes them through the same lexer that handles user input.
     */
    Map<Integer, String> defaults();

    /** {@code (sbe.template_id)} value, or {@code -1} if the message is not an SBE template. */
    int sbeTemplateId();

    /** Field number → {@code (sbe.length)} byte length, where set. */
    Map<Integer, Integer> sbeFieldLengths();

    /** Field number → {@code (sbe.encoding)} primitive name, where set. */
    Map<Integer, String> sbeFieldEncodings();

    /**
     * Field number → declaring oneof name. Synthetic oneofs around proto3
     * {@code optional} fields are excluded; only user-declared oneof
     * groupings appear here.
     */
    Map<Integer, String> oneofOf();

    /**
     * The proto package + simple name of the described message, e.g.
     * {@code "sample.Person"}. Useful for diagnostics and for resolving
     * cross-message references in {@link #messageTypes()}.
     */
    String fullName();

    /**
     * Field number → {@link PxfMeta} of the target nested message type, for
     * fields of kind 11 (MESSAGE). Generated {@code <Message>PxfMeta} classes
     * populate this with direct {@code <Sub>PxfMeta.INSTANCE} references at
     * codegen time, so the runtime can recurse into nested messages without
     * a separate {@link PxfRegistry} lookup. Default returns {@link Map#of()}
     * — implementors that don't expose embedded references fall back to the
     * registry path.
     */
    default Map<Integer, PxfMeta> nestedMetas() {
        return Map.of();
    }

    /**
     * Field number → {@link PxfEnum} of the target enum type, for fields of
     * kind 14 (ENUM). Same shape and rationale as {@link #nestedMetas()};
     * default returns {@link Map#of()}.
     */
    default Map<Integer, PxfEnum> enumMetas() {
        return Map.of();
    }
}
